### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by vtroop** [ziwenxie/leafer#1]
clone下来后，更改数据库，输入admin 123456密码，永远跳转在login界面

**Comment by ziwenxie** [comment]
:+1: 
不好意思，`leafer.sql`写错了，请在数据库中执行`INSERT INTO user(id, username, password) VALUES(1, 'admin', '$2a$10$MDSRJE0SGzRWWMRdfZVq2.yfYOBQ8Y/6UMgONnmrzKMJbcB/Wi7i6');`，然后使用`admin 123456`登录看一看。

如果还不行我再排查一下原因。

**Comment by vtroop** [comment]
:)，多谢，测试已经解决
