### ISSUE TITLE
输入的中文全变成问号了

### ISSUE THREAD

**Issue by wjg1101766085** [ziwenxie/leafer#2]

**Comment by ziwenxie** [comment]
这应该是MySQL乱码的原因，请尝试将MySQL的默认编码改成utf-8试一试  :-)

**Comment by wjg1101766085** [comment]
不是这个问题。我mysql是设置的utf-8编码~~

**Comment by ziwenxie** [comment]
@wjg1101766085 输入英文的话能正常显示么？截下图看一看

**Comment by wjg1101766085** [comment]
解决方案：spring.datasource.url=jdbc:mysql://HOST:PORT/leafer?characterEncoding=utf8&useSSL=false

**Comment by ziwenxie** [comment]
嗯，现在问题解决了么?

**Comment by wjg1101766085** [comment]
解决了。我找了一圈。然后发现后面没设置mysql的编码。这个是建议增加的。。
