### ISSUE TITLE
Save posts in files.

### ISSUE THREAD

**Issue by gaojiuli** [ziwenxie/leafer#3]
I don't want to save my posts in databese because I will publish them on my blog or bbs. Meanwhile, maybe I want to edit the markdown files with another editor such as atom. So could leafer provide the option to set where I want to save my posts in?

**Comment by ziwenxie** [comment]
Got it

I'll add a function to make `leafer` support to export a specific article to a file. But it will take a few days. :-)

**Comment by wjg1101766085** [comment]
I think you can save the data to sqlite。。

**Comment by zhangyingwei** [comment]
I also think you can save the data to sqlite。。

**Comment by gaojiuli** [comment]
@wjg1101766085 
@zhangyingwei 

What if I need editing the markdown files with another editor such as atom ?

**Comment by ziwenxie** [comment]
@zhangyingwei @zhangyingwei 

Well...

But I want to deploy `leafer` in produce situation in the future so that everyone can use it. Performance problem must be considered :P

**Comment by wjg1101766085** [comment]
@gaojiuli 
I suggest that you can use atom editing after the copy to leafer
