### ISSUE TITLE
非登录用户的访问地址是什么, 编辑完在页面上会显示markdown 语法

### ISSUE THREAD

**Issue by cloud-lzq** [ziwenxie/leafer#5]
![image](https://user-images.githubusercontent.com/8512430/27470405-531c9642-5826-11e7-94e8-68f0a6c547eb.png)

![image](https://user-images.githubusercontent.com/8512430/27470427-63051282-5826-11e7-824e-659069be704f.png)

**Comment by ziwenxie** [comment]
1. 和描述中所述一样leafer现在是一个`一个私人笔记管理项目`，或许以后会考虑添加分享功能。

2. 上面是不是两张图片？刷新一下截取全屏看一看。

**Comment by cloud-lzq** [comment]
是两张图片第一张是home 显示效果, 第二张是点开之后的效果

这个是刷新后的结果.
![image](https://user-images.githubusercontent.com/8512430/27471580-c581d478-582a-11e7-83b1-f27d6c23936f.png)

我以为这个是个人博客系统, 看你那个博客挺漂亮的.

**Comment by ziwenxie** [comment]
暑假的话会考虑增加分享功能，在首页的话只会显示前100个字方便浏览，如果每篇文章都去解析markdown语法的话太耗时间了。
