### ISSUE TITLE
test

### ISSUE THREAD

**Issue by zkh26** [ziwenxie/leafer#6]
我测试的时候怎么会有乱码啊

**Comment by ziwenxie** [comment]
先看下这个问题 => https://github.com/ziwenxie/leafer/issues/2

修改一下编码

**Comment by zkh26** [comment]
添加了之后可以了，那你那边为什么不在配置中添加上去呢，还有Springboot不是可以配置成热启动吗，应该可以弄个吧

**Comment by zkh26** [comment]
刚才将数据库中的数据给删掉了，然后发现程序就挂掉了哦，

**Comment by ziwenxie** [comment]
等下会更新一下readme，因为之前都是在mac和linux下测试没有出现过乱码情况。

**Comment by zkh26** [comment]
我怎么感觉我这本地的程序很容易就挂掉了呢，

--- spring-boot-maven-plugin:1.5.3.RELEASE:run (default-cli) @ leafer ---
[INFO] Attaching agents: []
Exception in thread "main" java.lang.Error: Unresolved compilation problem: 

	at org.ziwenxie.leafer.Application.main(Application.java:10)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.586 s
[INFO] Finished at: 2017-06-23T18:08:13+08:00
[INFO] Final Memory: 21M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.5.3.RELEASE:run (default-cli) on project leafer: Could not exec java: Application finished with exit code: 1 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

帮忙看下。。/wx

**Comment by ziwenxie** [comment]
@zkh26 
直接`git clone https://github.com/ziwenxie/leafer`后重新编译，你这样每次在eclipse后修改代码再贴报错信息我也没有这么多精力来解决。
